language: node_js
node_js:
  - "4.1"
install:
  - npm i -g mocha mongodb
  - npm i
script:
  - npm test
branches:
  only:
    - master
notifications:
  email: false
  slack:
    rooms:
      - jdmc-team:uDadFX5DSkCQ4bnZFJwOEISx
    on_success: change # default: always
    on_failure: always # default: always
after_success:
  - scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q -r package* public app views index.js setupMockDB.js root@grant.mhi.io:~/grantman
services:
  - mongodb
