language: node_js
node_js:
  - "4.1"
install:
  - npm i -g mocha mongodb
  - npm i
script:
  - npm test
notifications:
  email: false
  slack: jdmc-team:uDadFX5DSkCQ4bnZFJwOEISx
after_success:
  - scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q -r package* views index.js root@grant.mhi.io:~/grantman
